= BASIC EventShareOS Example
This is an example implementation of the Event Share Operating System for POSIX systems. 

The Code is written in C and should compile on most systems.  The original code was written on a Ubantu Linux desktop.  

== BASIC Demo
The code uses two modules, the main module handles soft timer events and keyboard inputs.  The second module reads the keyboard and sends keyboard events. 

There are two special keys used to bring up the menu and quit the program. 


== Program Design

The main program is the application module, or app for short.  The program design is very simple, the keyboard_module reads the keyboard and sends event reads to the application.  

The application processes timer events and keyboards and display them on the terminal. 

Timers are typically repeating, and to demonstrate one shot timers, ever so many repeats of the repeating timer a one shot timer is started. 

[mermaid]
----
graph
timers --> app;
app --> timers
keyboard --> app;
app --> terminal;
----

